#!/bin/bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $AIRFLOW_DB_USER WITH PASSWORD '$AIRFLOW_DB_PASSWORD';
    CREATE DATABASE $AIRFLOW_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $AIRFLOW_DB_NAME TO $AIRFLOW_DB_USER;
    CREATE USER $MLFLOW_DB_USER WITH PASSWORD '$MLFLOW_DB_PASSWORD';
    CREATE DATABASE $MLFLOW_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $MLFLOW_DB_NAME TO $MLFLOW_DB_USER;
EOSQL